config/routes.rb
Rails.application.routes.draw do
  resources :renters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get 'renters/:id' => 'renters#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/renter.rb
class Renter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/renters_controller.rb
class RentersController < ApplicationController

    # before_action :current_renter, only: [:show,:edit,:update,:destroy]

    def index
        @renters = Renter.all
    end
    
    def show
        @renter = Renter.find(params[:id])
    end

    def new
        @renter = Renter.new
    end

    def create
        @renter = Renter.create(renter_params)

        redirect_to renter_path(@renter)
    end

    def edit
        @renter = Renter.find(params[:id])
    end

    def update
        @renter = Renter.find(params[:id])
        @renter.update

        redirect_to renter_path(@renter)
    end

    def destroy
        @renter = Renter.find(params[:id])
        @renter.destroy

        redirect_to renter_path
    end

    private
        def renter_params
            params.require(:renter).permit(:name, :room_number)
        end

        # def current_renter
        #     @renter = Renter.find(params[:id])
        # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/renters_helper.rb
module RentersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentersApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/renters/edit.html.erb
<h3>Edit a Renter</h3>
<%= form_for @renter do |f| %>
  <p>Enter Renter's New Name: <%= f.text_field :name %></p>
  <p>Enter Renter's Room Number: <%= f.text_field :room_number %></p>

  <%= f.submit %>
<% end %>

app/views/renters/index.html.erb
<table>
  <% @renters.each do |renter| %>
    <tr>
      <td><%= link_to renter.name, renter_path(renter) %></td>
      <td><%= button_to 'Edit', edit_renter_path(renter), method: 'get'%></td>
      <td><%= button_to 'Remove', renter_path(renter), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Renter", new_renter_path %>

app/views/renters/new.html.erb
<h3>Create a Renter</h3>
<%= form_for @renter do |f| %>
  <p>Enter Renter's Name: <%= f.text_field :name, placeholder: "renter name" %></p>
  <p>Enter Renter's Room Number: <%= f.text_field :room_number, placeholder: "room number" %></p>

  <%= f.submit %>
<% end %>

app/views/renters/show.html.erb
<h2>Name: <%= @renter.name%></h2>
<h4>Room Number: <%= @renter.room_number%></h4>

<%= button_to "All Renters", renters_path, method: :get %>
<%= button_to "Edit Renter", edit_renter_path(@renter), method: :get %>
<%= button_to 'Remove Renter', renter_path(@renter), method: 'delete', data: { confirm: 'Are you sure?' } %>